name: ADF Deployment Workflow

on:
  push:
    branches:
      - adf_publish

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-az-cli@v1

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 

      - name: Get Azure subscription details
        run: az account show --query "{subscriptionId:id, tenantId:tenantId}" -o json
        id: get_sub_details
        env:
          AZURE_HTTP_USER_AGENT: "GITHUBACTIONS_${{ github.action }}"

      - name: Set Azure subscription
        run: az account set --subscription ${{ steps.get_sub_details.outputs.subscriptionId }}

      - name: Download ARM template
        run: |
          mkdir -p arm-template
          az resource export --ids ${{ secrets.AZURE_SOURCE_DATA_FACTORY_ID }} --api-version 2018-06-01 --resource-type "Microsoft.DataFactory/factories" --file "arm-template/factory.json"

      - name: Deploy to target Azure Data Factory
        run: |
          az deployment group create --resource-group ${{ secrets.AZURE_TARGET_RESOURCE_GROUP }} --template-file "arm-template/factory.json" --parameters "arm-template/parameters.json" --name "premal-prod" --verbose
